---
version: "3.1"
services:

  plex-meta-manager:
    image: lscr.io/linuxserver/plex-meta-manager:latest
    container_name: plex-meta-manager
    environment:
      - PUID=998
      - PGID=13000
      - TZ=US/Mountain
      - PMM_RUN=true
    volumes:
      - /mnt/md0/Servarr/config/pmm-config:/config
    restart: unless-stopped